### PR TITLE
Remove `enable` and make it more convenient

### PR DESCRIPTION
**Pull request by minamorl**
Solves #3

### CODE REVIEW

**Comment by PhilippMDoerner** [comment]
I think this is something very similar to the Observable before, but different enough to warrant being its own thing.

In RXJS terms I would describe what you previously had as a mixture of Observable (because it can hold a value, but in RXJS you can't push new values through them) and Subject (because you can push new values through them, in RXJS those can't hold values that would be replayed on initial subscribe).

This is what you'd define as a [BehaviorSubject](https://reactivex.io/documentation/subject.html) - You can push new values through them and it retains the last value.

Depending on if you want to grow your library to have different kinds of reactive types for different scenarios similar to RXJS, you may want to look into having multiple different types that all implement `subscribe`, `next` (for Observable that one is optional), and `create`.

That is just an avenue you can go down though. The current approach of replacing your prior Observable/Subject mix with this being a BehaviorSubject also works, particularly since BehaviorSubject is very much the most valuable and flexible of the reactive types (in my opinion).

**Comment by PhilippMDoerner** [comment]
As a general sidenote, there's some folks that also dabble in reactive programming in the nim discord server/matrix channels (Rika comes to mind specifically because she also was pondering how to go about it with reactive programming in nim).

She might also be able to provide valuable feedback/ideas !

**Comment by minamorl** [comment]
Thanks for the feedback. I'd like to discuss on it as the separated issue.

**Comment by PhilippMDoerner** [comment]
sure!

**Pull request merged**
